INSERT INTO `empresas` (
    `empresacod`,
    `empresarut`,
    `razonsocial`,
    `giro`,
    `empresaemail`,
    `contactonombre`,
    `contactoemail`,
    `contactocelular`,
    `empresaiderp`,
    `empapikeyhash`,
    `empapikeyactiva`,
    `empapikeyfechagen`,
    `empapikeyultuso`,
    `empapikeyipultuso`,
    `empresaactivo`,
    `auditcreacionusuarioid`,
    `auditcreaciondispositivo`,
    `auditcreacionip`
  )
  VALUES (
    '76459811-3',
    '76459811-3',
    'CAPAC SPA',
    'CULTIVO DE OTRAS PLANTAS PERENNES',
    'contacto@puduhue.cl',
    'Alexis Pérez',
    'alexis.perez@puduhue.cl',
    '+56912345678',
    'PRUEB39',
    '',
    0,
    NOW(),
    NOW(),
    '',
    1,
    '0',
    'system',
    '127.0.0.1'
  );