CREATE TABLE IF NOT EXISTS `erpmonedas` (
  `erpmonedaid` int(11) NOT NULL AUTO_INCREMENT,
  `erpmonedacod` varchar(50) NOT NULL COMMENT 'Codigo ERP de moneda',
  `erpmonedadsc` varchar(100) NOT NULL COMMENT 'Nombre visible desde ERP',
  `erpmonedadescripcion` varchar(255) NULL DEFAULT NULL COMMENT 'Descripcion adicional desde ERP',
  `erpmonedadefault` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1=Moneda default operativa para Compras',
  `erpmonedaactivo` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Activo segun ERP',
  `sincfechahora` datetime NULL DEFAULT NULL COMMENT 'Ultima sincronizacion ERP',
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL DEFAULT NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NULL DEFAULT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NULL DEFAULT NULL COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`erpmonedaid`),
  UNIQUE KEY `uq_erpmonedas_cod` (`erpmonedacod`),
  KEY `idx_erpmonedas_activo` (`erpmonedaactivo`),
  KEY `idx_erpmonedas_default` (`erpmonedadefault`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
