CREATE TABLE `empresas` (
  `empresaid` int(11) NOT NULL AUTO_INCREMENT,
  `empresacod` varchar(12) NOT NULL COMMENT 'Lo mismo que el Rut',
  `empresarut` varchar(12) NOT NULL,
  `razonsocial` varchar(100) NOT NULL,
  `giro` varchar(100) NOT NULL,
  `empresaemail` varchar(100) NOT NULL COMMENT 'Requerido para crear el usuario con el Rut de la empresa',
  `contactonombre` varchar(100) NOT NULL,
  `contactoemail` varchar(100) NOT NULL,
  `contactocelular` varchar(12) NOT NULL,
  `empresaiderp` varchar(50) NOT NULL COMMENT 'Columna que se usa para la integraci�n',
  `empapikeyhash` varchar(255) NOT NULL,
  `empapikeyactiva` tinyint(1) NOT NULL DEFAULT 1,
  `empapikeyfechagen` datetime NOT NULL,
  `empapikeyultuso` datetime NOT NULL COMMENT 'Fecha Hora ultimo uso',
  `empapikeyipultuso` varchar(50) NOT NULL COMMENT 'IP ultimo uso',
  `empresaactivo` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Si esta activo el registro',
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`empresaid`),
  UNIQUE KEY `uq_empresas_empresarut` (`empresarut`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
