CREATE TABLE IF NOT EXISTS `centroscosto` (
  `centrocostoid` int(11) NOT NULL AUTO_INCREMENT,
  `empresaid` int(11) NULL DEFAULT NULL COMMENT 'FK local a empresas; pendiente de regla de asignacion',
  `centrocostocod` varchar(50) NOT NULL COMMENT 'Codigo visible local',
  `centrocostodsc` varchar(100) NOT NULL COMMENT 'Nombre visible desde ERP',
  `centrocostodescripcion` varchar(255) NULL DEFAULT NULL COMMENT 'Descripcion adicional desde ERP',
  `erpcentrocostocod` varchar(50) NOT NULL COMMENT 'Codigo ERP de centro de costo / DIMCTC si aplica',
  `centrocostojefeusuarioid` int(11) NULL DEFAULT NULL COMMENT 'Atributo local; jefe firmante por defecto',
  `centrocostojefetecnicoid` int(11) NULL DEFAULT NULL COMMENT 'Atributo local pendiente de definicion funcional',
  `centrocostogerenteproduccionid` int(11) NULL DEFAULT NULL COMMENT 'Atributo local pendiente de definicion funcional',
  `centrocostoactivo` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Activo segun ERP',
  `sincfechahora` datetime NULL DEFAULT NULL COMMENT 'Ultima sincronizacion ERP',
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL DEFAULT NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NULL DEFAULT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NULL DEFAULT NULL COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`centrocostoid`),
  UNIQUE KEY `uq_centroscosto_erp_codigo` (`erpcentrocostocod`),
  KEY `idx_centroscosto_empresa` (`empresaid`),
  KEY `idx_centroscosto_activo` (`centrocostoactivo`),
  KEY `idx_centroscosto_jefe` (`centrocostojefeusuarioid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
