CREATE TABLE `invitems` (
  `invitemid` int(11) NOT NULL AUTO_INCREMENT,
  `invitemdsc` varchar(50) NOT NULL,
  `invunidmedid` int(11) NOT NULL,
  `erpinvitemcod` varchar(50) NOT NULL COMMENT 'Codigo que corresponde al ERP, para despues usar en las integraciones',
  `invitemleche` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Para utilizar en el modulo de Leche',
  `invitemstockeable` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Para utilizar en el modulo de Suplementación animal. Solo = 1 si el ítem maneja stock',
  `invitemusocodigo` varchar(10) NOT NULL DEFAULT 'BDG' COMMENT 'Uso funcional local: BDG=bodega/base, LCH=leche, ALM=suplementacion animal, CMB=combustible',
  `familiaid` int(11) NULL DEFAULT NULL COMMENT 'FK a familias sincronizada desde ERP Producto',
  `subfamiliaid` int(11) NULL DEFAULT NULL COMMENT 'FK a subfamilias sincronizada desde ERP Producto',
  `erptasaimpositivaid` int(11) NULL DEFAULT NULL COMMENT 'FK a tasa impositiva ERP para compras/PreOC',
  `erppartidafinancieraid` int(11) NULL DEFAULT NULL COMMENT 'FK a DIMPARFIN para DimensionDistribucion en PreOC',
  `invitemcompra` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1=Producto utilizable en compras/PreOC',
  `invitemcostoestandar` decimal(18,4) NOT NULL DEFAULT 0.0000 COMMENT 'Costo estandar ERP o manual si ERP no informa valor',
  `invitemcostoestandarfechahora` datetime NULL DEFAULT NULL COMMENT 'Fecha/hora ultima actualizacion costo estandar',
  `invitemactivo` tinyint(1) NOT NULL DEFAULT 1,
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`invitemid`),
  KEY `idx_invitems_usocodigo` (`invitemusocodigo`),
  KEY `idx_invitems_familiaid` (`familiaid`),
  KEY `idx_invitems_subfamiliaid` (`subfamiliaid`),
  KEY `idx_invitems_erptasaimpositivaid` (`erptasaimpositivaid`),
  KEY `idx_invitems_erppartidafinancieraid` (`erppartidafinancieraid`),
  KEY `idx_invitems_compra` (`invitemcompra`),
  KEY `idx_invitems_invunidmedid` (`invunidmedid`),
  CONSTRAINT `fk_invitems_invunidmedid` FOREIGN KEY (`invunidmedid`) REFERENCES `invunidadesmedidas` (`invunidmedid`),
  CONSTRAINT `fk_invitems_familiaid` FOREIGN KEY (`familiaid`) REFERENCES `familias` (`familiaid`) ON DELETE SET NULL,
  CONSTRAINT `fk_invitems_subfamiliaid` FOREIGN KEY (`subfamiliaid`) REFERENCES `subfamilias` (`subfamiliaid`) ON DELETE SET NULL,
  CONSTRAINT `fk_invitems_erptasaimpositivaid` FOREIGN KEY (`erptasaimpositivaid`) REFERENCES `erptasasimpositivas` (`erptasaimpositivaid`) ON DELETE SET NULL,
  CONSTRAINT `fk_invitems_erppartidafinancieraid` FOREIGN KEY (`erppartidafinancieraid`) REFERENCES `erppartidasfinancieras` (`erppartidafinancieraid`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
