CREATE TABLE `retirolechedetalle` (
  `retirolecheid` int(11) NOT NULL AUTO_INCREMENT,
  `empresaid` int(11) NOT NULL,
  `fundoid` int(11) NOT NULL,
  `fundoestanqueid` int(11) NOT NULL,
  `clienteid` int(11) NOT NULL,
  `estanqueclientecod` int(11) NOT NULL COMMENT 'Codigo interno del cliente asociado al estanque al momento del retiro',
  `retirolechefecha` datetime NOT NULL,
  `retirolechehoraini` time NOT NULL,
  `retirolechehorafin` time NOT NULL,
  `retirolechelitros` int(6) NOT NULL,
  `retirolechetemperatura` float NOT NULL,
  `retirolecheobservacion` varchar(100) NOT NULL,
  `retirolechefoto` varchar(255) NOT NULL COMMENT 'Nombre del archivo con us extensión que se almacena dentro de la ruta "uploads/retiroleche/img/<crear carpeta con el ID>"',
  `retirolechestatus` varchar(3) NOT NULL DEFAULT 'CN' COMMENT 'CN: Confirmada | ANL: Anulada',
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP  on update current_timestamp() COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`retirolecheid`),
  KEY `idx_retiroleche_empresaid` (`empresaid`),
  CONSTRAINT `fk_retirolechedet_empresaid` FOREIGN KEY (`empresaid`) REFERENCES `empresas` (`empresaid`),
  KEY `idx_retiroleche_fundoid` (`fundoid`),
  CONSTRAINT `fk_retirolechedet_fundoid` FOREIGN KEY (`fundoid`) REFERENCES `fundos` (`fundoid`),
  KEY `idx_retirolechedetalle_fundoestanqueid` (`fundoestanqueid`),
  CONSTRAINT `fk_retirolechedetalle_fundoestanqueid` FOREIGN KEY (`fundoestanqueid`) REFERENCES `fundosestanques` (`fundoestanqueid`),
  KEY `idx_retirolechedetalledet_clienteid` (`clienteid`),
  CONSTRAINT `fk_retirolechedetalle_clienteid` FOREIGN KEY (`clienteid`) REFERENCES `clientes` (`clienteid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'Retiro de Leche Planta - Detalle';
