CREATE TABLE `suplanimal` (
  `suplanimalid` int(11) NOT NULL AUTO_INCREMENT,
  `suplanimalstatus` varchar(3) NOT NULL COMMENT 'CN: Confirmada | ANL: Anulada | PND: Pendiente ERP',
  `empresaid` int(11) NOT NULL,
  `fundoid` int(11) NOT NULL,
  `invbodegaid` int(11) NOT NULL,
  `suplanimalfecha` datetime NOT NULL,
  `suplanimalobservacion` varchar(50) NOT NULL,
  `sup_erpestablecimientocod` varchar(50) NOT NULL COMMENT 'Se obtiene desde el fundo seleccionado: fundos.erpestablecimientocod',
  `sup_erplotecod` varchar(50) NOT NULL COMMENT 'Se obtiene desde el fundo seleccionado: fundos.erplotecod',
  `sup_erpinvbodegacod` varchar(50) NOT NULL COMMENT 'Se obtiene desde la Bodega seleccionada: invbodegas.erpinvbodegacod',
  `suplanml_erp_sync` datetime NULL COMMENT 'Fecha y hora de la sincronizacion al ERP',
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`suplanimalid`),
  KEY `idx_suplanimal_empresaid` (`empresaid`),
  CONSTRAINT `fk_suplanimal_empresaid` FOREIGN KEY (`empresaid`) REFERENCES `empresas` (`empresaid`),
  KEY `idx_suplanimal_fundoid` (`fundoid`),
  CONSTRAINT `fk_suplanimal_fundoid` FOREIGN KEY (`fundoid`) REFERENCES `fundos` (`fundoid`),
  KEY `idx_suplanimal_invbodegaid` (`invbodegaid`),
  CONSTRAINT `fk_suplanimal_invbodegaid` FOREIGN KEY (`invbodegaid`) REFERENCES `invbodegas` (`invbodegaid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'Suplementaci�n de animales - Encabezado';
