CREATE TABLE IF NOT EXISTS `erplistadoendpoints` (
  `erpendpointid` int(11) NOT NULL AUTO_INCREMENT,
  `erpendpointcodigo` varchar(50) NOT NULL COMMENT 'Codigo funcional interno del endpoint',
  `erpendpointdescripcion` varchar(150) NOT NULL,
  `erpendpointrecurso` varchar(255) NOT NULL COMMENT 'Path/recurso sin ACCESS_TOKEN. Ej: /api/producto/list',
  `erpendpointmetodo` varchar(10) NOT NULL DEFAULT 'GET' COMMENT 'GET | POST',
  `erpendpointtipo` varchar(20) NOT NULL COMMENT 'BASE_ERP | CUSTOM | REPORT_VIEWER',
  `erpendpointproposito` varchar(20) NOT NULL COMMENT 'MAESTRO_GET | DETALLE_GET | TRANSACCION_POST',
  `erpendpointgrupoid` int(11) NOT NULL DEFAULT 0,
  `erpendpointorden` int(11) NOT NULL DEFAULT 0,
  `erpendpointpadreid` int(11) NULL DEFAULT NULL,
  `erpendpointrequierecodigo` tinyint(1) NOT NULL DEFAULT 0,
  `erpendpointpermiteondemand` tinyint(1) NOT NULL DEFAULT 1,
  `erpendpointpermiteauto` tinyint(1) NOT NULL DEFAULT 0,
  `erpendpointfrecuencia` varchar(20) NULL DEFAULT NULL COMMENT 'DIARIO | SEMANAL | MENSUAL',
  `erpendpointdiaevento` varchar(20) NULL DEFAULT NULL,
  `erpendpointhoraevento` time NULL DEFAULT NULL,
  `erpendpointformulariocall` varchar(100) NULL DEFAULT NULL,
  `erpendpointjsonarchivoejemplo` varchar(150) NULL DEFAULT NULL,
  `erpendpointultsync` datetime NULL DEFAULT NULL,
  `erpendpointultestado` varchar(20) NULL DEFAULT NULL COMMENT 'OK | ERROR | PARCIAL',
  `erpendpointulterror` text NULL DEFAULT NULL,
  `erpendpointactivo` tinyint(1) NOT NULL DEFAULT 1,
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NULL DEFAULT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NULL DEFAULT NULL COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`erpendpointid`),
  UNIQUE KEY `uq_erplistadoendpoints_codigo` (`erpendpointcodigo`),
  UNIQUE KEY `uq_erplistadoendpoints_grupo_orden` (`erpendpointgrupoid`, `erpendpointorden`),
  KEY `idx_erplistadoendpoints_padreid` (`erpendpointpadreid`),
  KEY `idx_erplistadoendpoints_formulario` (`erpendpointformulariocall`),
  KEY `idx_erplistadoendpoints_activo` (`erpendpointactivo`),
  CONSTRAINT `fk_erplistadoendpoints_padreid`
    FOREIGN KEY (`erpendpointpadreid`) REFERENCES `erplistadoendpoints` (`erpendpointid`)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
