CREATE TABLE `fundos` (
  `fundoid` int(11) NOT NULL AUTO_INCREMENT,
  `fundonombre` varchar(50) NOT NULL,
  `fundotipoid` int(11) NOT NULL,
  `empresaid` int(11) NOT NULL,
  `erpestablecimientocod` varchar(50) NOT NULL COMMENT 'C�digo que corresponde al ERP, para despues usar en las integraciones',
  `erplotecod` varchar(50) NOT NULL COMMENT 'C�digo que corresponde al ERP, para despues usar en las integraciones',
  `erpleche_invbodegacod` varchar(50) NOT NULL COMMENT 'C�digo que corresponde al ERP, para despues usar en las integraciones',
  `erpleche_invcateganimalcod` varchar(50) NOT NULL COMMENT 'C�digo que corresponde al ERP, para despues usar en las integraciones',
  `fundopabco` tinyint(1) NOT NULL DEFAULT 0,
  `fundorup` varchar(50) NOT NULL,
  `fundoregion` varchar(50) NOT NULL,
  `fundoprovincia` varchar(50) NOT NULL,
  `fundocomuna` varchar(50) NOT NULL,
  `fundodireccion` varchar(100) NOT NULL,
  `fundolatitud` float NOT NULL,
  `fundolongitud` float NOT NULL,
  `fundoemail` varchar(100) NOT NULL,
  `fundoactivo` tinyint(1) NOT NULL DEFAULT 1,
  `reporteorden` int(4) NOT NULL DEFAULT 0,
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`fundoid`),
  KEY `idx_fundos_fundotipoid` (`fundotipoid`),
  CONSTRAINT `fk_fundos_fundotipoid` FOREIGN KEY (`fundotipoid`) REFERENCES `fundostipos` (`fundotipoid`),
  KEY `idx_fundos_empresaid` (`empresaid`),
  CONSTRAINT `fk_fundos_empresaid` FOREIGN KEY (`empresaid`) REFERENCES `empresas` (`empresaid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
