-- ALTER TABLE prodleche AUTO_INCREMENT = 1;
CREATE TABLE `prodleche` (
  `prodlecheid` int(11) NOT NULL AUTO_INCREMENT,
  `prodlechestatus` varchar(3) NOT NULL COMMENT 'CN: Confirmada | ANL: Anulada | PND: Pendiente ERP',
  `empresaid` int(11) NOT NULL,
  `fundoid` int(11) NOT NULL,
  `prodlechefecha` datetime NOT NULL,
  `prodlechehoraini` time NOT NULL,
  `prodlechehorafin` time NOT NULL,
  `prodlechehorario` char(2) NOT NULL COMMENT 'Se calcula con la fecha hora de inicio de orde�a: AM/PM',
  `pl_erpestablecimientocod` varchar(50) NOT NULL COMMENT 'Se obtiene desde el fundo seleccionado: fundos.erpestablecimientocod',
  `pl_erplotecod` varchar(50) NOT NULL COMMENT 'Se obtiene desde el fundo seleccionado: fundos.erplotecod',
  `pl_erpleche_invbodegacod` varchar(50) NOT NULL COMMENT 'Se obtiene desde el fundo seleccionado: fundos.erpleche_invbodegacod',
  `pl_erpleche_invcateganimalcod` varchar(50) NOT NULL COMMENT 'Se obtiene desde el fundo seleccionado: fundos.erpleche_invcateganimalcod',
  `prodlechetotlitros` int(6) NOT NULL COMMENT 'Suma de todos los litros en tabla detalle: "prodlechedetalle.pldetlitros" independiente del tipo de leche',
  `prodlechetotvacas` int(4) NOT NULL COMMENT 'Suma de todos los litros en tabla detalle: "prodlechedetalle.pldetvacas" independiente del tipo de leche',
  `prodlecheventatotlitros` int(6) NOT NULL COMMENT 'Suma los Litros en tabla detalle: "prodlechedetalle.pldetlitros" where prodlechetipos.prodlecheventa = 1 group by prodlechetipos.prodlechetipoid',
  `prodlecheventatotvacas` int(4) NOT NULL COMMENT 'Suma las Vacas en tabla detalle: "prodlechedetalle.pldetvacas" where prodlechetipos.prodlecheventa = 1 group by prodlechetipos.prodlechetipoid',
  `prodlecheventalitrosxvaca` float NOT NULL COMMENT 'Promedio de Litros x Vaca en tabla detalle: "prodlechedetalle.pldetlitrosxvaca" where prodlechetipos.prodlecheventa = 1 group by prodlechetipos.prodlechetipoid',
  `prodlecheobservacion` varchar(50) NOT NULL,
  `pl_erp_sync` datetime NULL COMMENT 'Fecha y hora de la sincronizacion al ERP',
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`prodlecheid`),
  KEY `idx_prodleche_empresaid` (`empresaid`),
  CONSTRAINT `fk_prodleche_empresaid` FOREIGN KEY (`empresaid`) REFERENCES `empresas` (`empresaid`),
  KEY `idx_prodleche_fundoid` (`fundoid`),
  CONSTRAINT `fk_prodleche_fundoid` FOREIGN KEY (`fundoid`) REFERENCES `fundos` (`fundoid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
