CREATE TABLE `invitems` (
  `invitemid` int(11) NOT NULL AUTO_INCREMENT,
  `invitemdsc` varchar(50) NOT NULL,
  `invunidmedid` int(11) NOT NULL,
  `erpinvitemcod` varchar(50) NOT NULL COMMENT 'Codigo que corresponde al ERP, para despues usar en las integraciones',
  `invitemleche` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Para utilizar en el modulo de Leche',
  `invitemstockeable` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Para utilizar en el modulo de Suplementación animal. Solo = 1 si el ítem maneja stock',
  `invitemactivo` tinyint(1) NOT NULL DEFAULT 1,
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`invitemid`),
  KEY `idx_invitems_invunidmedid` (`invunidmedid`),
  CONSTRAINT `fk_invitems_invunidmedid` FOREIGN KEY (`invunidmedid`) REFERENCES `invunidadesmedidas` (`invunidmedid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
