CREATE TABLE `usuarios` (
  `usuarioid` int(11) NOT NULL AUTO_INCREMENT,
  `usuariocod` varchar(12) NOT NULL COMMENT 'Usado en el Login',
  `usuariorut` varchar(12) NOT NULL,
  `usuarionombre` varchar(100) NOT NULL,
  `usuariopwdhash` varchar(255) NOT NULL COMMENT 'Contrase�a encriptada',
  `usuarioemail` varchar(100) NOT NULL,
  `usuariocelular` varchar(12) NOT NULL,
  `perfilid` int(11) NOT NULL,
  `empresaiddefault` int(11) NULL DEFAULT NULL COMMENT 'Una empresa default asociada al usuario para el Login',
  `fundoiddefault` int(11) NULL DEFAULT NULL COMMENT 'Un fundo default asociado al usuario para el Login',
  `usuarioesroot` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Solo puede haber un usuario ROOT',
  `usuarioesadmin` tinyint(1) NOT NULL DEFAULT 0,
  `usuariobloqueado` tinyint(1) NOT NULL DEFAULT 0,
  `usuariobloqueadodesc` varchar(100) NOT NULL,
  `intentosfallidos` smallint(1) NOT NULL DEFAULT 0,
  `usuarioultimologin` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `usuarioultimopwdcambio` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `usuariopwdproxvenc` datetime NOT NULL DEFAULT '1900-01-01 00:00:00',
  `usuarioapikeyhash` varchar(255) NOT NULL,
  `usuarioapikeyactiva` tinyint(1) NOT NULL DEFAULT 1,
  `usuarioapikeyfechagen` datetime NOT NULL,
  `usuarioapikeyultuso` datetime NOT NULL,
  `usuarioapikeyipultuso` varchar(50) NOT NULL,
  `usuarioactivo` tinyint(1) NOT NULL DEFAULT 1,
  `auditcreacionusuarioid` int(11) NOT NULL COMMENT 'p_in_usuarioid',
  `auditcreaciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditcreacionip` varchar(50) NOT NULL COMMENT 'IP del PC',
  `auditcreacionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de INS',
  `auditedicionusuarioid` int(11) NULL COMMENT 'p_in_usuarioid',
  `auditediciondispositivo` varchar(100) NOT NULL COMMENT 'Dispositivo nombre',
  `auditedicionip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP del PC',
  `auditedicionfechahora` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha hora de UPD',
  PRIMARY KEY (`usuarioid`),
  UNIQUE KEY `uq_usuarios_usuariorut` (`usuariorut`),
  UNIQUE KEY `uq_usuarios_usuarioesroot` (`usuarioesroot`),
  KEY `idx_usuarios_perfilid` (`perfilid`),
  CONSTRAINT `fk_usuarios_perfilid` FOREIGN KEY (`perfilid`) REFERENCES `perfiles` (`perfilid`),
  KEY `idx_usuarios_empresaiddefault` (`empresaiddefault`),
  CONSTRAINT `fk_usuarios_empresaiddefault` FOREIGN KEY (`empresaiddefault`) REFERENCES `empresas` (`empresaid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
